name: Docker Image CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
      matrix:
        install4j: [8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.0.7]
        imagebase: [adoptopenjdk/openjdk11, maven]
        imageversion: [slim, 3.6.3-adoptopenjdk-11]
        exclude:
          - imagebase: adoptopenjdk/openjdk11
            imageversion: 3.6.3-adoptopenjdk-11
          - imagebase: maven
            imageversion: slim
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          add_git_labels: true
          registry: docker.pkg.github.com
          repository: ricardf/docker-install4j/install4j
          tags: ${{ matrix.install4j }}
          buildargs: INSTALL4J_VERSION=${{ matrix.install4j }}, IMAGE_BASE=${{ matrix.imagebase }}, IMAGE_VERSION=${{ matrix.imageversion }}